# Generated by Django 6.0 on 2026-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentformat',
            old_name='bracket',
            new_name='bracket_stage',
        ),
        migrations.RenameField(
            model_name='tournamentformat',
            old_name='groups',
            new_name='groups_stage',
        ),
        migrations.AddField(
            model_name='tournamentformat',
            name='is_seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentformat',
            name='bracket_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tournamentformat',
            name='groups_results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
