# Generated by Django 6.0 on 2026-04-16 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_bracket_tournamentformat_bracket_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolmembership',
            options={'verbose_name': 'Pool Membership', 'verbose_name_plural': 'Pool Memberships'},
        ),
        migrations.RenameField(
            model_name='tournamentplay',
            old_name='score',
            new_name='bracket_points',
        ),
        migrations.AddField(
            model_name='poolmembership',
            name='has_paid',
            field=models.BooleanField(default=False, help_text='Tracks if the user has paid the entry fee for this specific play.'),
        ),
        migrations.AddField(
            model_name='tournamentplay',
            name='group_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='allow_multiple_plays_per_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='cost_per_play',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='is_money_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='members',
            field=models.ManyToManyField(related_name='pools', through='tournament.PoolMembership', to='tournament.tournamentplay'),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_memberships', to='tournament.tournamentplay'),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='tournament.tournamentpool'),
        ),
        migrations.AlterField(
            model_name='tournamentplay',
            name='name',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='tournamentpool',
            name='name',
            field=models.CharField(max_length=42),
        ),
        migrations.AddConstraint(
            model_name='tournamentplay',
            constraint=models.UniqueConstraint(fields=('user', 'tournament', 'name'), name='unique_play_name_per_user_per_tournament'),
        ),
    ]
