# Generated by Django 6.0 on 2026-04-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_poolmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpool',
            name='join_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
