# Generated by Django 6.0 on 2026-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentpool_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplay',
            name='name',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='tournamentpool',
            name='name',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
