# Generated by Django 6.0 on 2026-05-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_tournamentplay_name_alter_tournamentpool_name'),
        ('tournament', '0012_tournament_status_choices'),
    ]

    operations = [
    ]
