# Generated by Django 6.0.5 on 2026-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_merge_0007_branches'),
        ('tournament', '0013_merge_20260518_0914'),
    ]

    operations = [
    ]
