# Generated by Django 6.0 on 2026-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=1, help_text='Number of times user has logged in'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook')], help_text='OAuth provider used for authentication', max_length=20, null=True),
        ),
    ]
