# Generated by Django 6.0 on 2026-05-07 10:06

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_login_count_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_edited_username',
            field=models.BooleanField(default=False, help_text='Whether the user has manually changed their username at least once'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Number of times user has logged in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 21 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=21, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
