# Generated by Django 6.0 on 2026-03-24 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamescore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, help_text="Name of the game (e.g., 'snake', 'tetris', 'pong')", max_length=100)),
                ('score', models.IntegerField(help_text="Player's score for this game session")),
                ('game_metadata', models.JSONField(blank=True, default=dict, help_text='Additional game-specific data (level reached, time played, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamescores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamescore',
                'verbose_name_plural': 'Gamescores',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['game_name', '-score'], name='highscores__game_na_a38610_idx'), models.Index(fields=['user', 'game_name', '-created_at'], name='highscores__user_id_35b713_idx'), models.Index(fields=['user', '-created_at'], name='highscores__user_id_0d22e8_idx')],
            },
        ),
    ]
