# Generated by Django 6.0 on 2026-02-11 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highscore',
            new_name='Gamescore',
        ),
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'Gamescore', 'verbose_name_plural': 'Gamescores'},
        ),
        migrations.RenameIndex(
            model_name='gamescore',
            new_name='highscores__game_na_a38610_idx',
            old_name='highscores__game_na_8174eb_idx',
        ),
        migrations.RenameIndex(
            model_name='gamescore',
            new_name='highscores__user_id_35b713_idx',
            old_name='highscores__user_id_7dbd39_idx',
        ),
        migrations.RenameIndex(
            model_name='gamescore',
            new_name='highscores__user_id_0d22e8_idx',
            old_name='highscores__user_id_973727_idx',
        ),
    ]
