# Generated by Django 6.0 on 2026-03-24 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-game_score', '-created_at'], 'verbose_name': 'Gamescore', 'verbose_name_plural': 'Gamescores'},
        ),
        migrations.RemoveIndex(
            model_name='gamescore',
            name='highscores__game_na_a38610_idx',
        ),
        migrations.RenameField(
            model_name='gamescore',
            old_name='score',
            new_name='game_score',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='game_time',
            field=models.CharField(default=0, help_text='Time spent in this game session (in seconds)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['game_name', '-game_score'], name='highscores__game_na_b6534a_idx'),
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='updated_at',
        ),
    ]
